#querying from dependency track list of projects
name: Dependency Track


on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Query from DT
      env:
        DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEP_TRACK_TOKEN }}
        UUID: e31cecde-9ba5-45ea-816f-7d1d10fb5fe9
      run: | 
        API_CALL=https://dtapi.northdepot.ca/api/v1/vulnerability/project/$UUID
        echo "Fetching vulnerabilities... from $API_CALL"
        
        echo "X-Api-Key: $DEPENDENCY_TRACK_API_KEY" > header 
        curl -H @header  "$API_CALL"  
